# Generated by Django 3.2.7 on 2021-09-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210901_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyrecord',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
